spring:
  application:
    name: batch-admin-console

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle10gDialect
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@(DESCRIPTION=(SDU=32767)(RECV_BUF_SIZE=65536)(SEND_BUF_SIZE=65536)(ADDRESS=(PROTOCOL=TCP)(HOST=prm-lsf-ota-ora-03.idm.promedico.nl)(PORT=1521))(CONNECT_DATA=(SERVICE_NAME=PROMDEV1.idm.promedico.nl)))
    username: tst02_biexport
    password: his

  batch:
    job:
      enabled: false

server:
  port: 8081
  servlet:
    context-path: /admin-console